## Lecture 2: Intro to Optimization

Goal: to motivate the use of an optimization framework in imaging. 

In [182]:
## MP 574 Lecture 2: Intro to optimization
##
%matplotlib inline
import numpy as np
import scipy.linalg as la
import numpy.random as rnd
import matplotlib.pyplot as plt
from IPython.display import display, Image
import matplotlib.image as mpimg
from os.path import dirname, join as pjoin
import scipy.io as sio

In [183]:
A = [[1, 4, 5, 12], 
    [-5, 8, 9, 0],
    [-6, 7, 11, 19]]


In [184]:
la.null_space(A)

array([[-0.23174056],
       [ 0.65590855],
       [-0.71177458],
       [ 0.09724827]])

In [199]:
b= np.array([0, 1, 2, 3])
y = np.array([-1, 0.2, 0.9, 2.1])
b = np.random.rand(3,1)
A = np.random.rand(3,2)
x = np.linalg.lstsq(A, b, rcond=None)

In [201]:
x

(array([[-0.29783349],
        [ 1.97790238]]),
 array([0.18282723]),
 2,
 array([1.5246864 , 0.25989249]))